### ISSUE TITLE
[Debug] rendering html in dd

### ISSUE THREAD

**Issue by tenmajkl** [Lemon-Framework/Lemon#111]
dont render html in dd

**Comment by TENMAJKL** [comment]
dd also for some reason crashes whole webserver

**Comment by TENMAJKL** [comment]
also we need to fix private properties hack

**Comment by TENMAJKL** [comment]
ok dd probably has some problem with cycle orm object ok

**Comment by tenmajkl** [comment]
I should probably rewrite the whole thing
