### ISSUE TITLE
[Router] dynamic prefix

### ISSUE THREAD

**Issue by TENMAJKL** [Lemon-Framework/Lemon#115]
I'm working on project, where would be handy to have dymanic prefix in Route::controller. Obviously it would be on every collection, but on controllers it would save me 1 line of code. 

```php
Route::controller("forgotten-password/{token}", ForgotenPassword::class);
```

instead of

```php
Route::get("forgotten-password/{token}", [ForgotenPassword::class, 'get']);
Route::post("forgotten-password/{token}", [ForgotenPassword::class, 'post']);
```

**Comment by TENMAJKL** [comment]
I don't think its nessesary, but it should be simple to implement, but I don't have time to do it.

**Comment by TENMAJKL** [comment]
Well, but I need to save my 1 line of code. And your duty as maintainer should be to implement stuff that people need.

**Comment by TENMAJKL** [comment]
I'm sorry, but I have big project that I need to do, I will do only fixes that are nesscesary for my project until february. If you really want to do this, you can.

**Comment by TENMAJKL** [comment]
Well, I also have big project and don't have time. I don't care about your projects, just do it, or I will remove star!!!!!

**Comment by TENMAJKL** [comment]
YOU ASSIGN YOURSELF IN #116 AND DONT HAVE TIME FOR THIS CRITICAL THING????

**Comment by TENMAJKL** [comment]
I'm sorry, but that has much bigger priority, because it produces serious bug. And if you have time to post this, you have time to that thing.

**Comment by TENMAJKL** [comment]
OK, I'll do it then.

**Comment by VietScripts** [comment]
Majkle, uklidni se :DDD

**Comment by TENMAJKL** [comment]
OK, its probably not that simple to do and not even nescesary.

**Comment by TENMAJKL** [comment]
Alright, I'll close the issue then.

**Comment by TENMAJKL** [comment]
OK, this issue was kinda joke, I wanted to actually implement it, and make fun of it. Then I tried to implement it and it was too difficult for so unnescesary thing. I will maybe do it when I rewrite router.
