### ISSUE TITLE
Cache $data property type is unfit

### ISSUE THREAD

**Issue by harabisj** [Lemon-Framework/Lemon#162]
**src/Lemon/Cache/Cache.php line 59** assignes result of `json_decode()` to $data property of type array, however the return value of the function does not have to be an array (for example "null" is a valid JSON content being decoded into `null`).

**Comment by tenmajkl** [comment]
is there any actual situation where can the file contain literal null?

**Comment by tenmajkl** [comment]
Because I think that unless you directly write it to the file, its impossible for null to apear there.

**Comment by harabisj** [comment]
I'm not 100 % sure, however this code should raise the exception:
```
Cache::set('key', null);
Cache::get('key');
```

**Comment by tenmajkl** [comment]
I think it sould be ok

**Comment by harabisj** [comment]
Right, mentioned code does not produce the error.

**Comment by harabisj** [comment]
The problem is in syntactically malformed data.json file. Currently I am unsure, how the error occurred. If the issue reappears, I'll reopen it.
