### ISSUE TITLE
__toString() has been deprecated

### ISSUE THREAD

**Issue by ordago** [Lemon-Framework/Lemon#42]
https://github.com/Lemon-Framework/Lemon/blob/fc610730730ad42af95e775359575a86c7234e9a/src/Http/Routing/Helpers.php#L24

>This function has been DEPRECATED as of PHP 7.1.0. Relying on this function is highly discouraged.

https://www.php.net/manual/en/reflectiontype.tostring.php

**Comment by TENMAJKL** [comment]
Fixed in [version 3](https://github.com/Lemon-Framework/Lemon/blob/8b6f13958ca3c0004547450f44a313c9c3e6797f/src/Lemon/Support/Http/Routing/Helpers.php#L24)
