### ISSUE TITLE
Routing via strings

### ISSUE THREAD

**Issue by TENMAJKL** [Lemon-Framework/Lemon#48]
CoolFido had an idea to generate routes via something like Route::get("/foo > FooController:get") so why not literaly writing syntax 🤔

**Comment by CoolFido** [comment]
Actually I imagined it as something like this:
```
/ > HomeController
page/{page} > PagesController:show
```
We could shrink that down to:
```
/ HomeController
page/{page} PagesController:show
```

**Comment by TENMAJKL** [comment]
@CoolFido this is literaly the highest possible level that syntax can be. Change my mind

**Comment by CoolFido** [comment]
Not true, that might be
```
posts with comments by user
pages
```

**Comment by TENMAJKL** [comment]
Ok, let's just write emails

**Comment by CoolFido** [comment]
php lemonade Hello, I'd like my web app to have posts with comments by users and pages. Thanks.

**Comment by TENMAJKL** [comment]
Looks like challenge. I'd start with regex and then create neuron network that will build app in Lemon. I will do it in php with no dependency excepts pest for tests

**Comment by TENMAJKL** [comment]
I will propably leave the routing as it is and improve controllers.
